# Docker Compose file Reference (https://docs.docker.com/compose/compose-file/)

version: '3.7'

# Define services
services:
  # Backend service
  app-backend:
    # Configuration for building the docker image for the backend service
    build:
      context: BackEnd # Use an image built from the specified dockerfile in the `BackEnd` directory.
      dockerfile: Dockerfile-BackEnd
    ports:
      - "8080:8080" # Forward the exposed port 8080 on the container to port 8080 on the host machine
    restart: always
    depends_on: 
      - db # This service depends on mysql. Start that first.
    environment: # Pass environment variables to the service
      SPRING_DATASOURCE_URL: jdbc:mysql://localhost:3306/Baloot_Shopping_Center_DB
    networks: # Networks to join (Services on the same network can communicate with each other using their name)
      - backend
      - frontend

  # Frontend Service 
  app-frontend:
    build:
      context: FrontEnd # Use an image built from the specified dockerfile in the `FrontEnd` Docker file.
      dockerfile: Dockerfile-FrontEnd
      args:
        REACT_APP_API_BASE_URL: http://192.168.99.100:8080
    ports:
      - "9090:80" # Forward the exposed port 80 on the container to port 80 on the host machine
    restart: always
    depends_on:
      - app-backend
    networks:
      - frontend  

  # Database Service (Mysql)
  db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    restart: always
    environment:
      MYSQL_DATABASE: baloot_shopping_center_db
      MYSQL_ROOT_PASSWORD: Ariya1234567890
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - backend  
  
# Volumes
volumes:
  db-data:

# Networks to be created to facilitate communication between containers
networks:
  backend:
  frontend:    